// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *Footer → CTA Section*
 */
export interface FooterDocumentDataCtaSectionItem {
  /**
   * Eyebrow Text field in *Footer → CTA Section*
   *
   * - **Field Type**: Text
   * - **Placeholder**: WORK WITH US
   * - **API ID Path**: footer.cta_section[].eyebrow_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow_text: prismic.KeyTextField;

  /**
   * CTA Title field in *Footer → CTA Section*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Ready to optimise your logistics?
   * - **API ID Path**: footer.cta_section[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * CTA Description field in *Footer → CTA Section*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Our logistics experts are ready to provide a customised quote...
   * - **API ID Path**: footer.cta_section[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Primary Button Text field in *Footer → CTA Section*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Get a Quote
   * - **API ID Path**: footer.cta_section[].primary_button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  primary_button_text: prismic.KeyTextField;

  /**
   * Primary Button Link field in *Footer → CTA Section*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.cta_section[].primary_button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary Button Text field in *Footer → CTA Section*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Tracking
   * - **API ID Path**: footer.cta_section[].secondary_button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondary_button_text: prismic.KeyTextField;

  /**
   * Secondary Button Link field in *Footer → CTA Section*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.cta_section[].secondary_button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondary_button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Background Image (Optional) field in *Footer → CTA Section*
   *
   * - **Field Type**: Image
   * - **Placeholder**: Optional background image for the CTA section
   * - **API ID Path**: footer.cta_section[].background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Item in *Footer → Solutions Section → Solution Links*
 */
export interface FooterDocumentDataSolutionsSectionLinksItem {
  /**
   * Link Text field in *Footer → Solutions Section → Solution Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Ocean Freight, National Road Freight, etc.
   * - **API ID Path**: footer.solutions_section[].links[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link URL field in *Footer → Solutions Section → Solution Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.solutions_section[].links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Footer → Solutions Section*
 */
export interface FooterDocumentDataSolutionsSectionItem {
  /**
   * Section Title field in *Footer → Solutions Section*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Solutions
   * - **API ID Path**: footer.solutions_section[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Solution Links field in *Footer → Solutions Section*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.solutions_section[].links[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  links: prismic.NestedGroupField<
    Simplify<FooterDocumentDataSolutionsSectionLinksItem>
  >;
}

/**
 * Item in *Footer → Specialties Section → Specialty Links*
 */
export interface FooterDocumentDataSpecialtiesSectionLinksItem {
  /**
   * Link Text field in *Footer → Specialties Section → Specialty Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Customs & AQIS, Over Dimensional Cargo, etc.
   * - **API ID Path**: footer.specialties_section[].links[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link URL field in *Footer → Specialties Section → Specialty Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.specialties_section[].links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Footer → Specialties Section*
 */
export interface FooterDocumentDataSpecialtiesSectionItem {
  /**
   * Section Title field in *Footer → Specialties Section*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Specialties
   * - **API ID Path**: footer.specialties_section[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Specialty Links field in *Footer → Specialties Section*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.specialties_section[].links[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  links: prismic.NestedGroupField<
    Simplify<FooterDocumentDataSpecialtiesSectionLinksItem>
  >;
}

/**
 * Item in *Footer → Contact Section → Locations*
 */
export interface FooterDocumentDataContactSectionLocationsItem {
  /**
   * Location Name field in *Footer → Contact Section → Locations*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Brisbane Warehouse, Geelong Depot
   * - **API ID Path**: footer.contact_section[].locations[].location_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  location_name: prismic.KeyTextField;

  /**
   * Address field in *Footer → Contact Section → Locations*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 186 Boundary Road Rocklea, QLD 4106
   * - **API ID Path**: footer.contact_section[].locations[].address
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  address: prismic.KeyTextField;

  /**
   * Phone Number field in *Footer → Contact Section → Locations*
   *
   * - **Field Type**: Text
   * - **Placeholder**: +61 7 3517 0604
   * - **API ID Path**: footer.contact_section[].locations[].phone
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  phone: prismic.KeyTextField;
}

/**
 * Item in *Footer → Contact Section → Additional Information*
 */
export interface FooterDocumentDataContactSectionAdditionalInfoItem {
  /**
   * Info Label field in *Footer → Contact Section → Additional Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Import & Export, Locations
   * - **API ID Path**: footer.contact_section[].additional_info[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *Footer → Contact Section*
 */
export interface FooterDocumentDataContactSectionItem {
  /**
   * Section Title field in *Footer → Contact Section*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Contact Us
   * - **API ID Path**: footer.contact_section[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Locations field in *Footer → Contact Section*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contact_section[].locations[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  locations: prismic.NestedGroupField<
    Simplify<FooterDocumentDataContactSectionLocationsItem>
  >;

  /**
   * Additional Information field in *Footer → Contact Section*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contact_section[].additional_info[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  additional_info: prismic.NestedGroupField<
    Simplify<FooterDocumentDataContactSectionAdditionalInfoItem>
  >;
}

/**
 * Item in *Footer → Legal Links*
 */
export interface FooterDocumentDataLegalLinksItem {
  /**
   * Link Text field in *Footer → Legal Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Privacy Policy, Terms of Service
   * - **API ID Path**: footer.legal_links[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link URL field in *Footer → Legal Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.legal_links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Footer → Website Credit*
 */
export interface FooterDocumentDataWebsiteCreditItem {
  /**
   * Credit Text field in *Footer → Website Credit*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Website by
   * - **API ID Path**: footer.website_credit[].text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;

  /**
   * Link Text field in *Footer → Website Credit*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Phantom
   * - **API ID Path**: footer.website_credit[].link_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  link_text: prismic.KeyTextField;

  /**
   * Credit Link field in *Footer → Website Credit*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.website_credit[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * CTA Section field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.cta_section[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cta_section: prismic.GroupField<Simplify<FooterDocumentDataCtaSectionItem>>;

  /**
   * Footer Logo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Solutions Section field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.solutions_section[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  solutions_section: prismic.GroupField<
    Simplify<FooterDocumentDataSolutionsSectionItem>
  >;

  /**
   * Specialties Section field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.specialties_section[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  specialties_section: prismic.GroupField<
    Simplify<FooterDocumentDataSpecialtiesSectionItem>
  >;

  /**
   * Contact Section field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contact_section[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  contact_section: prismic.GroupField<
    Simplify<FooterDocumentDataContactSectionItem>
  >;

  /**
   * Legal Links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.legal_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  legal_links: prismic.GroupField<Simplify<FooterDocumentDataLegalLinksItem>>;

  /**
   * Copyright Text field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: © MACH1 Logistics Pty Ltd. All rights reserved.
   * - **API ID Path**: footer.copyright_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  copyright_text: prismic.KeyTextField;

  /**
   * Website Credit field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.website_credit[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  website_credit: prismic.GroupField<
    Simplify<FooterDocumentDataWebsiteCreditItem>
  >;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Item in *Header → Navigation Menu → Dropdown Items*
 */
export interface HeaderDocumentDataNavigationDropdownItemsItem {
  /**
   * Dropdown Item Label field in *Header → Navigation Menu → Dropdown Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Customs & AQIS, Over Dimensional Cargo, etc.
   * - **API ID Path**: header.navigation[].dropdown_items[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Dropdown Item Link field in *Header → Navigation Menu → Dropdown Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Select a page or enter URL
   * - **API ID Path**: header.navigation[].dropdown_items[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Item Image field in *Header → Navigation Menu → Dropdown Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: Image that appears when hovering this item
   * - **API ID Path**: header.navigation[].dropdown_items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *Header → Navigation Menu*
 */
export interface HeaderDocumentDataNavigationItem {
  /**
   * Menu Item Label field in *Header → Navigation Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Home, About, Services, etc.
   * - **API ID Path**: header.navigation[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Menu Item Link field in *Header → Navigation Menu*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Select a page or enter URL
   * - **API ID Path**: header.navigation[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Has Dropdown Menu field in *Header → Navigation Menu*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: header.navigation[].has_dropdown
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  has_dropdown: prismic.BooleanField;

  /**
   * Dropdown Title (Optional) field in *Header → Navigation Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Custom title for dropdown header (defaults to menu item label if empty)
   * - **API ID Path**: header.navigation[].dropdown_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  dropdown_title: prismic.KeyTextField;

  /**
   * Dropdown Items field in *Header → Navigation Menu*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navigation[].dropdown_items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  dropdown_items: prismic.NestedGroupField<
    Simplify<HeaderDocumentDataNavigationDropdownItemsItem>
  >;

  /**
   * Dropdown Image (Optional) field in *Header → Navigation Menu*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navigation[].dropdown_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  dropdown_image: prismic.ImageField<never>;
}

/**
 * Item in *Header → Header Buttons*
 */
export interface HeaderDocumentDataButtonsItem {
  /**
   * Button Text field in *Header → Header Buttons*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Get A Quote, Tracking, etc.
   * - **API ID Path**: header.buttons[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Button Link field in *Header → Header Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Select a page or enter URL
   * - **API ID Path**: header.buttons[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Site Title field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter your site title
   * - **API ID Path**: header.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  site_title: prismic.KeyTextField;

  /**
   * Logo field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Navigation Menu field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navigation: prismic.GroupField<Simplify<HeaderDocumentDataNavigationItem>>;

  /**
   * Header Buttons field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.buttons[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  buttons: prismic.GroupField<Simplify<HeaderDocumentDataButtonsItem>>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type HomeDocumentDataSlicesSlice = HeroSlice | SolutionsSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type PageDocumentDataSlicesSlice =
  | ImageWithTextSlice
  | ContentBlockSlice
  | OurTeamSlice
  | HeroSlice
  | ImageClippedSlice
  | LocationsSlice
  | ServicesSlice
  | SolutionsSlice
  | StatisticsSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type SolutionDocumentDataSlicesSlice =
  | ImageClippedSlice
  | StatisticsSlice
  | ServicesSlice
  | HeroSlice
  | SolutionsSlice;

/**
 * Content for Solution documents
 */
interface SolutionDocumentData {
  /**
   * Title field in *Solution*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Solution title
   * - **API ID Path**: solution.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Solution*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Brief description of the solution
   * - **API ID Path**: solution.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Featured Image field in *Solution*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: solution.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<"card">;

  /**
   * Category field in *Solution*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Freight, Logistics, Transportation
   * - **API ID Path**: solution.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  category: prismic.KeyTextField;

  /**
   * Slice Zone field in *Solution*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: solution.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<SolutionDocumentDataSlicesSlice> /**
   * Meta Title field in *Solution*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: solution.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Solution*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: solution.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Solution*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: solution.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Solution document from Prismic
 *
 * - **API ID**: `solution`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SolutionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SolutionDocumentData>,
    "solution",
    Lang
  >;

export type AllDocumentTypes =
  | FooterDocument
  | HeaderDocument
  | HomeDocument
  | PageDocument
  | SolutionDocument;

/**
 * Primary content in *ContentBlock → Default → Primary*
 */
export interface ContentBlockSliceDefaultPrimary {
  /**
   * Heading field in *ContentBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Decades of dedication to Australian business.
   * - **API ID Path**: content_block.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Subheading field in *ContentBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: OUR STORY
   * - **API ID Path**: content_block.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheading: prismic.KeyTextField;

  /**
   * Description field in *ContentBlock → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Since our early days, Mach1 has been committed to one goal: making logistics work better for Australian companies.
   * - **API ID Path**: content_block.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Text Alignment field in *ContentBlock → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose text alignment
   * - **Default Value**: left
   * - **API ID Path**: content_block.default.primary.text_alignment
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  text_alignment: prismic.SelectField<"left" | "center" | "right", "filled">;

  /**
   * Content Width field in *ContentBlock → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose content width
   * - **Default Value**: full
   * - **API ID Path**: content_block.default.primary.content_width
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  content_width: prismic.SelectField<
    "full" | "three-quarters" | "two-thirds" | "half" | "one-third",
    "filled"
  >;

  /**
   * Top Margin field in *ContentBlock → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose top margin
   * - **Default Value**: large
   * - **API ID Path**: content_block.default.primary.margin_top
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  margin_top: prismic.SelectField<
    "none" | "small" | "medium" | "large" | "extra-large",
    "filled"
  >;

  /**
   * Show Image field in *ContentBlock → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: content_block.default.primary.show_image
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_image: prismic.BooleanField;

  /**
   * Full Width Image field in *ContentBlock → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content_block.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Show Bottom Separator field in *ContentBlock → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: content_block.default.primary.show_bottom_separator
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_bottom_separator: prismic.BooleanField;
}

/**
 * Default variation for ContentBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContentBlock*
 */
type ContentBlockSliceVariation = ContentBlockSliceDefault;

/**
 * ContentBlock Shared Slice
 *
 * - **API ID**: `content_block`
 * - **Description**: Reusable content block with optional image, flexible text alignment, and separator toggles
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentBlockSlice = prismic.SharedSlice<
  "content_block",
  ContentBlockSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Subheading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: SUBHEADING
   * - **API ID Path**: hero.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheading: prismic.KeyTextField;

  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: The Mach 1 Difference
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Our experienced team develops customised solutions, that save you time and money.
   * - **API ID Path**: hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *Hero → Items*
 */
export interface HeroSliceDefaultItem {
  /**
   * Slideshow Image field in *Hero → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default hero layout
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  Simplify<HeroSliceDefaultItem>
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero section with unique layout
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *ImageClipped → Default → Primary*
 */
export interface ImageClippedSliceDefaultPrimary {
  /**
   * Heading (Optional) field in *ImageClipped → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional heading above the image
   * - **API ID Path**: image_clipped.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Image field in *ImageClipped → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_clipped.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Caption (Optional) field in *ImageClipped → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional caption below the image
   * - **API ID Path**: image_clipped.default.primary.caption
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  caption: prismic.KeyTextField;

  /**
   * Priority Loading field in *ImageClipped → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_clipped.default.primary.priority_loading
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  priority_loading: prismic.BooleanField;
}

/**
 * Default variation for ImageClipped Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default image with geometric clipping
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageClippedSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageClippedSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageClipped*
 */
type ImageClippedSliceVariation = ImageClippedSliceDefault;

/**
 * ImageClipped Shared Slice
 *
 * - **API ID**: `image_clipped`
 * - **Description**: Image slice with geometric SVG clipping path
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageClippedSlice = prismic.SharedSlice<
  "image_clipped",
  ImageClippedSliceVariation
>;

/**
 * Primary content in *ImageWithText → Default → Primary*
 */
export interface ImageWithTextSliceDefaultPrimary {
  /**
   * Heading field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: About Us
   * - **API ID Path**: image_with_text.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Subheading field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: BUILT ON RELATIONSHIPS
   * - **API ID Path**: image_with_text.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheading: prismic.KeyTextField;

  /**
	 * Description field in *ImageWithText → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: The conception of Ron Firestone Transport signalled the re-emergence of Ron Firestone back into the transport industry following the sale of Firestone Holdings in 2001, the company went he built from the ground up during the 1960s.
	
	With our head office located in Wodonga on the New South Wales/Victoria border, directly in the centre of the Sydney, Melbourne Adelaide freight triangle, RFT provides regional and inter-capital city line-haul transport services across two major operating divisions - Food, Produce (either ambient or temperature controlled) & Manufactured Goods and Bulk Liquids.
	 * - **API ID Path**: image_with_text.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
  description: prismic.KeyTextField;

  /**
   * Layout Direction field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose layout direction
   * - **Default Value**: image-left
   * - **API ID Path**: image_with_text.default.primary.layout_direction
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  layout_direction: prismic.SelectField<"image-left" | "text-left", "filled">;

  /**
   * Top Margin field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: Choose top margin
   * - **Default Value**: large
   * - **API ID Path**: image_with_text.default.primary.margin_top
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  margin_top: prismic.SelectField<
    "none" | "small" | "medium" | "large" | "extra-large",
    "filled"
  >;

  /**
   * Image field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Show Bottom Separator field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_with_text.default.primary.show_bottom_separator
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_bottom_separator: prismic.BooleanField;
}

/**
 * Default variation for ImageWithText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageWithTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageWithTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageWithText*
 */
type ImageWithTextSliceVariation = ImageWithTextSliceDefault;

/**
 * ImageWithText Shared Slice
 *
 * - **API ID**: `image_with_text`
 * - **Description**: Image and text layout with flexible positioning and clipped image shape
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImageWithTextSlice = prismic.SharedSlice<
  "image_with_text",
  ImageWithTextSliceVariation
>;

/**
 * Primary content in *Locations → Default → Primary*
 */
export interface LocationsSliceDefaultPrimary {
  /**
   * Heading field in *Locations → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Where you can find us.
   * - **API ID Path**: locations.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Subheading field in *Locations → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: OUR LOCATIONS
   * - **API ID Path**: locations.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheading: prismic.KeyTextField;
}

/**
 * Primary content in *Locations → Items*
 */
export interface LocationsSliceDefaultItem {
  /**
   * Location Name field in *Locations → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Lancefield
   * - **API ID Path**: locations.items[].location_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  location_name: prismic.KeyTextField;

  /**
   * Location Type field in *Locations → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Head Office
   * - **API ID Path**: locations.items[].location_type
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  location_type: prismic.KeyTextField;

  /**
   * Address field in *Locations → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 13 High Street Lancefield, VIC 3435
   * - **API ID Path**: locations.items[].address
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  address: prismic.KeyTextField;

  /**
   * Phone field in *Locations → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: +61 3 5428 3680
   * - **API ID Path**: locations.items[].phone
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  phone: prismic.KeyTextField;

  /**
   * Email field in *Locations → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: admin@mach1logistics.com.au
   * - **API ID Path**: locations.items[].email
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email: prismic.KeyTextField;
}

/**
 * Default variation for Locations Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LocationsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LocationsSliceDefaultPrimary>,
  Simplify<LocationsSliceDefaultItem>
>;

/**
 * Slice variation for *Locations*
 */
type LocationsSliceVariation = LocationsSliceDefault;

/**
 * Locations Shared Slice
 *
 * - **API ID**: `locations`
 * - **Description**: Locations with map integration
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LocationsSlice = prismic.SharedSlice<
  "locations",
  LocationsSliceVariation
>;

/**
 * Primary content in *OurTeam → Default → Primary*
 */
export interface OurTeamSliceDefaultPrimary {
  /**
   * Heading field in *OurTeam → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Our leadership team.
   * - **API ID Path**: our_team.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Subheading field in *OurTeam → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: TEAM
   * - **API ID Path**: our_team.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheading: prismic.KeyTextField;

  /**
   * Description field in *OurTeam → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Follow the steps below and we will get a quote to you as soon as possible.
   * - **API ID Path**: our_team.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *OurTeam → Items*
 */
export interface OurTeamSliceDefaultItem {
  /**
   * Name field in *OurTeam → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Cheyne Warren
   * - **API ID Path**: our_team.items[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Position field in *OurTeam → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Founder
   * - **API ID Path**: our_team.items[].position
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  position: prismic.KeyTextField;

  /**
   * Profile Image field in *OurTeam → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_team.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for OurTeam Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OurTeamSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OurTeamSliceDefaultPrimary>,
  Simplify<OurTeamSliceDefaultItem>
>;

/**
 * Slice variation for *OurTeam*
 */
type OurTeamSliceVariation = OurTeamSliceDefault;

/**
 * OurTeam Shared Slice
 *
 * - **API ID**: `our_team`
 * - **Description**: Team members showcase with photos and positions
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OurTeamSlice = prismic.SharedSlice<
  "our_team",
  OurTeamSliceVariation
>;

/**
 * Primary content in *Services → Default → Primary*
 */
export interface ServicesSliceDefaultPrimary {
  /**
   * Section Heading field in *Services → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: How We Work
   * - **API ID Path**: services.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Section Description field in *Services → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Join our team to receive an above award remuneration and flexible work conditions.
   * - **API ID Path**: services.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Button Text field in *Services → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: SEE OUR NETWORK
   * - **API ID Path**: services.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *Services → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: services.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *Services → Items*
 */
export interface ServicesSliceDefaultItem {
  /**
   * Service Icon field in *Services → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.items[].service_icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  service_icon: prismic.ImageField<never>;

  /**
   * Service Title field in *Services → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: FCL import & export service
   * - **API ID Path**: services.items[].service_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  service_title: prismic.KeyTextField;

  /**
   * Service Description field in *Services → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Parcels, boxes, pallets. Importing and exporting solutions. Full Container Load (FCL) or Full Trailer Load (FTL) shipping. We've got you covered.
   * - **API ID Path**: services.items[].service_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  service_description: prismic.KeyTextField;
}

/**
 * Default variation for Services Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default services grid layout
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesSliceDefaultPrimary>,
  Simplify<ServicesSliceDefaultItem>
>;

/**
 * Slice variation for *Services*
 */
type ServicesSliceVariation = ServicesSliceDefault;

/**
 * Services Shared Slice
 *
 * - **API ID**: `services`
 * - **Description**: Services grid section with repeatable service items
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSlice = prismic.SharedSlice<
  "services",
  ServicesSliceVariation
>;

/**
 * Primary content in *Solutions → Default → Primary*
 */
export interface SolutionsSliceDefaultPrimary {
  /**
   * Subheading field in *Solutions → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: SOLUTIONS
   * - **API ID Path**: solutions.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheading: prismic.KeyTextField;

  /**
   * Heading field in *Solutions → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Our Freight Solutions
   * - **API ID Path**: solutions.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *Solutions → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Discover our comprehensive range of logistics and freight solutions
   * - **API ID Path**: solutions.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for Solutions Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default solutions grid layout
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SolutionsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SolutionsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Solutions*
 */
type SolutionsSliceVariation = SolutionsSliceDefault;

/**
 * Solutions Shared Slice
 *
 * - **API ID**: `solutions`
 * - **Description**: Display freight solutions in card format
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SolutionsSlice = prismic.SharedSlice<
  "solutions",
  SolutionsSliceVariation
>;

/**
 * Primary content in *Statistics → Default → Primary*
 */
export interface StatisticsSliceDefaultPrimary {
  /**
   * Subheading field in *Statistics → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: SHIPBROKING
   * - **API ID Path**: statistics.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheading: prismic.KeyTextField;

  /**
   * Main Heading field in *Statistics → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: The key contributors.
   * - **API ID Path**: statistics.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Description field in *Statistics → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: We are the leading provider in the market, with decades of experience and several satisfied customers. Our dedicated team of specialists is the largest in the world, responsible for completing thousands of successful trips.
   * - **API ID Path**: statistics.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *Statistics → Items*
 */
export interface StatisticsSliceDefaultItem {
  /**
   * Percentage field in *Statistics → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 35%+
   * - **API ID Path**: statistics.items[].percentage
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  percentage: prismic.KeyTextField;

  /**
   * Title field in *Statistics → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: IMPROVED EFFICIENCY
   * - **API ID Path**: statistics.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Statistics → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Drive efficiency at scale with hands-free, distraction-free focus.
   * - **API ID Path**: statistics.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for Statistics Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default statistics layout with cards
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StatisticsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StatisticsSliceDefaultPrimary>,
  Simplify<StatisticsSliceDefaultItem>
>;

/**
 * Slice variation for *Statistics*
 */
type StatisticsSliceVariation = StatisticsSliceDefault;

/**
 * Statistics Shared Slice
 *
 * - **API ID**: `statistics`
 * - **Description**: Statistics section with percentage cards and descriptions
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StatisticsSlice = prismic.SharedSlice<
  "statistics",
  StatisticsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataCtaSectionItem,
      FooterDocumentDataSolutionsSectionLinksItem,
      FooterDocumentDataSolutionsSectionItem,
      FooterDocumentDataSpecialtiesSectionLinksItem,
      FooterDocumentDataSpecialtiesSectionItem,
      FooterDocumentDataContactSectionLocationsItem,
      FooterDocumentDataContactSectionAdditionalInfoItem,
      FooterDocumentDataContactSectionItem,
      FooterDocumentDataLegalLinksItem,
      FooterDocumentDataWebsiteCreditItem,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataNavigationDropdownItemsItem,
      HeaderDocumentDataNavigationItem,
      HeaderDocumentDataButtonsItem,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SolutionDocument,
      SolutionDocumentData,
      SolutionDocumentDataSlicesSlice,
      AllDocumentTypes,
      ContentBlockSlice,
      ContentBlockSliceDefaultPrimary,
      ContentBlockSliceVariation,
      ContentBlockSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceDefaultItem,
      HeroSliceVariation,
      HeroSliceDefault,
      ImageClippedSlice,
      ImageClippedSliceDefaultPrimary,
      ImageClippedSliceVariation,
      ImageClippedSliceDefault,
      ImageWithTextSlice,
      ImageWithTextSliceDefaultPrimary,
      ImageWithTextSliceVariation,
      ImageWithTextSliceDefault,
      LocationsSlice,
      LocationsSliceDefaultPrimary,
      LocationsSliceDefaultItem,
      LocationsSliceVariation,
      LocationsSliceDefault,
      OurTeamSlice,
      OurTeamSliceDefaultPrimary,
      OurTeamSliceDefaultItem,
      OurTeamSliceVariation,
      OurTeamSliceDefault,
      ServicesSlice,
      ServicesSliceDefaultPrimary,
      ServicesSliceDefaultItem,
      ServicesSliceVariation,
      ServicesSliceDefault,
      SolutionsSlice,
      SolutionsSliceDefaultPrimary,
      SolutionsSliceVariation,
      SolutionsSliceDefault,
      StatisticsSlice,
      StatisticsSliceDefaultPrimary,
      StatisticsSliceDefaultItem,
      StatisticsSliceVariation,
      StatisticsSliceDefault,
    };
  }
}
