// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  careers: dynamic(() => import("./Careers")),
  contact_us: dynamic(() => import("./ContactUs")),
  content_block: dynamic(() => import("./ContentBlock")),
  faq: dynamic(() => import("./FAQ")),
  hero: dynamic(() => import("./Hero")),
  homepage_hero: dynamic(() => import("./HomepageHero")),
  image_carousel: dynamic(() => import("./ImageCarousel")),
  image_clipped: dynamic(() => import("./ImageClipped")),
  image_with_text: dynamic(() => import("./ImageWithText")),
  legal_content: dynamic(() => import("./LegalContent")),
  locations: dynamic(() => import("./Locations")),
  network: dynamic(() => import("./Network")),
  news: dynamic(() => import("./News")),
  our_team: dynamic(() => import("./OurTeam")),
  page_topper: dynamic(() => import("./PageTopper")),
  services: dynamic(() => import("./Services")),
  solutions: dynamic(() => import("./Solutions")),
  statistics: dynamic(() => import("./Statistics")),
  statistics_v2: dynamic(() => import("./StatisticsV2")),
  steps: dynamic(() => import("./Steps")),
  submitted: dynamic(() => import("./Submitted")),
  testimonials: dynamic(() => import("./Testimonials")),
  tracking: dynamic(() => import("./Tracking")),  
  news_overview: dynamic(() => import("./NewsOverview")),
  hero_block: dynamic(() => import("./HeroBlock")),
  
};
